### ISSUE TITLE
1.0.3的版本在Android Studio中加载不起

### ISSUE THREAD

**Issue by marcoaros** [lcodecorex/TwinklingRefreshLayout#12]
compile 'com.lcodecorex:tkrefreshlayout:1.0.3'
这个加载不了

**Comment by lcodecorex** [comment]
我这几个库的版本是appcompat-v7:23.2.0，recyclerview-v7:23.2.0，classpath 'com.android.tools.build:gradle:2.2.0'，看看是不是跟你的环境版本不对应
