### ISSUE TITLE
当不满一页时的刷新问题

### ISSUE THREAD

**Issue by NW0LC** [lcodecorex/TwinklingRefreshLayout#13]
当一页内容不满，上拉加载后，下拉就会是空白，松手后正常。不上拉就没这个问题

**Comment by lcodecorex** [comment]
收到，稍后修复这个问题

**Comment by lcodecorex** [comment]
@NW0LC 我试了之后没有复现这个问题。你嵌套的是什么View?数据较少时确实没有优化，稍后会修复这个问题

**Comment by NW0LC** [comment]
我上拉加载后 再去下拉，或者下拉再上拉，拉出来的布局就是空白的，没有出现刷新动画，松手动画就出现了，嵌套的是recycleview，防止我移植错误，我试过在下载下来的demo上干掉数据，只保留headerHolder里的数据（留一点数据可以上下拉），确实这个问题也出现了。如果你没能复现。。。那我也不知道问题出在哪里了/(ㄒoㄒ)/~~

**Comment by lcodecorex** [comment]
@NW0LC 好的。我再测试一下。这一版又该重构了
