### ISSUE TITLE
如何更改WebView上拉的时候那个可以越界的高度，可以自己修改吗？

### ISSUE THREAD

**Issue by zhejiushiwo** [lcodecorex/TwinklingRefreshLayout#15]

**Comment by zhejiushiwo** [comment]
楼主：你好，你的这个东西写的特别好，现在我遇到一个问题，用在WebView身上，让WebView上拉下拉出现回弹效果，能不能自己修改上拉越界的最大高度，我们的项目中这个高度还是有点低，希望能回答一下，着急使用，还有就是上拉和下拉的越界高度能不能一样的高

**Comment by lcodecorex** [comment]
好的，我check下。稍后答复你

**Comment by lcodecorex** [comment]
目前因为WebView fling滚动到底部的状态不好判断，所以fling到底部时是没有越界回弹，你可以setWaveHeight()、setBottomHeight()给顶部和底部设置同样的高度，比如etWaveHeight(80)、setBottomHeight(80)，这样上拉和下拉的越界高度就一样高了

**Comment by lcodecorex** [comment]
@zhejiushiwo 目前因为WebView fling滚动到底部的状态不好判断，所以fling到底部时是没有越界回弹，你可以setWaveHeight()、setBottomHeight()给顶部和底部设置同样的高度，比如etWaveHeight(80)、setBottomHeight(80)，这样上拉和下拉的越界高度就一样高了

**Comment by lcodecorex** [comment]
v1.04版发布，已优化问题！有彩蛋！！！
