### ISSUE TITLE
isOverlayRefreshShow可以改一下

### ISSUE THREAD

**Issue by anmingyu11** [lcodecorex/TwinklingRefreshLayout#16]
可以改成上下两种， 比如isOverlayRefreshShowBottm & isOverlayRefreshShowTop
这样可以更灵活的控制越界模式。
另外，这么好的项目竟然只有不到600star，一定要帮你宣传一下。

**Comment by lcodecorex** [comment]
@anmingyu11 感谢感谢！正在重构中，会及时添加你们反馈的功能的。
