### ISSUE TITLE
上拉加载更多后，动画有抽搐的感觉

### ISSUE THREAD

**Issue by 756718646** [lcodecorex/TwinklingRefreshLayout#17]
那个上拉加载更多，加载完成后，隐藏加载更多的动画，有抽搐回弹一下的感觉，那个动画可以弄平滑一点吗？或者动画支持自定义？

**Comment by lcodecorex** [comment]
@756718646 好的。正在考虑优化

**Comment by lcodecorex** [comment]
v1.04版已做优化发布，已修复问题！有彩蛋！！！
