### ISSUE TITLE
GoogleDotView有个地方写错了，造成内存泄漏

### ISSUE THREAD

**Issue by hxmeie** [lcodecorex/TwinklingRefreshLayout#18]
onPullingDown,onPullingRelease方法中  if (animator2.isRunning()) animator2.cancel();
你的是animator1.cancel();造成内存泄漏

**Comment by lcodecorex** [comment]
好的。这一版修复。感谢！

**Comment by lcodecorex** [comment]
@hxmeie v1.04版发布，已修复问题！有彩蛋！！！
