### ISSUE TITLE
快速滑动会产生滑动view的重叠

### ISSUE THREAD

**Issue by anmingyu11** [lcodecorex/TwinklingRefreshLayout#19]
这个是我们设计师发现的。。。。

复现步骤 ： 
比如说下拉刷新，
保持一定力度，快速的滑动（力度大小不能直接引起刷新） 会导致前后headerview 的重叠
我用超慢速摄影机看了一眼，
最终推测导致原因如下：
因为RefreshLayout缺少动画的中断机制，回弹的动画没有终止，再次下拉的时候就会出现这种情况，建议增加回弹动画的listenner
可以选择两种模式：
1.强行终止动画，将回弹设置为终止状态（SCROLL到初始位置0）
2.在动画终止之前禁止滑动，直到动画终止才可以进行滑动，可以在动画开始和结束时调整isrefresh的值（好像是这个）
3.可以设置这两种不同的滑动模式。

已经在app架构师上给你宣传了一下233，可以关注一下，我这边再帮你宣传宣传。

不知道上面这个问题你们注意到没有，如果没有开始改我有时间可以帮你们来修改这个问题，如果你们已经在做那我就等待啦，我的邮箱是349047303@qq.com 如果需要复现视频我可以发给你 ^_^

**Comment by anmingyu11** [comment]
还有，你的代码质量真的高，佩服佩服，学习了。

**Comment by lcodecorex** [comment]
@anmingyu11 非常感谢你的反馈。目前正在做重构，滑动的流畅性，动效的管理，都是要重点解决的问题，相信1.04版会给你们带来惊喜。😄
