### ISSUE TITLE
滑动冲突问题

### ISSUE THREAD

**Issue by MirrorFlower** [lcodecorex/TwinklingRefreshLayout#2]
如果顶部存在一个banner轮播的话，水平滑动banner容易触发下拉刷新

**Comment by TakWolf** [comment]
这是一个广泛性问题，大多数下拉刷新都有这个问题，包括google官方的swiftLayout

一种可用做法，滑动banner的时候，禁用下拉刷新，松手后恢复

**Comment by lcodecorex** [comment]
好的。稍晚一些我会进行一些测试和优化，争取能有一种更优的解法。

**Comment by MirrorFlower** [comment]
可以灵活的设置是否禁用上下拉就完美了 哈哈

**Comment by lcodecorex** [comment]
这个可以有😉

**Comment by bypain** [comment]
谷歌官方的SwipeRefreshLayout不存在滑动冲突吧

**Comment by MirrorFlower** [comment]
SwipeRefreshLayout和ViewPager存在滑动冲突的

**Comment by guoyoujin** [comment]
@TakWolf 看你头像有点像以前同事😄

**Comment by TakWolf** [comment]
@guoyoujin 是的，你没认错，就是我！！😄

**Comment by shenminjie** [comment]
支持！
