### ISSUE TITLE
fling时可以添加额外的setVelocity 来控制触发回弹的力度

### ISSUE THREAD

**Issue by anmingyu11** [lcodecorex/TwinklingRefreshLayout#20]
在检测fling的动作实现越界回弹时可以添加setFlingVelocity来控制力度。

希望能和up主沟通一下，希望能够贡献一些代码。

**Comment by lcodecorex** [comment]
@anmingyu11 正在重构，包括全新的UI，有代表性的动效，期待吧。下一版可以合作

**Comment by anmingyu11** [comment]
如果能贡献部分代码将是我的荣幸( ˘•ω•˘ )

**Comment by anmingyu11** [comment]
请问何时出下个版本？

**Comment by lcodecorex** [comment]
最迟会在这周周末，快重构完了

**Comment by anmingyu11** [comment]
我刚刚实现了类似于iphone的惯性回弹的效果，虽然还有触摸中断等没做，以后希望能加到你这个里面

**Comment by lcodecorex** [comment]
@anmingyu11 由于我正在做大重构，项目代码，结构改动比较大，你可以提交一个请求，我check下加入到现在的代码中。非常感谢你的帮助！新版功能与特性：

##### 新增功能
- **第二次重构完成**,将核心逻辑拆分为RefreshProcessor、AnimProcessor、OverScrollProcessor、CoProcessor
- **优化越界策越，手势决定越界高度**
- 添加类似SwipeRefreshLayout的**悬浮刷新**功能(ProgressLayout)
- 滑到底部**自动加载更多**or回弹可选，默认为回弹
- 将Head,Footer修改为设置位移，而不是设置高度
- 允许在结束刷新之前执行一个动效：IHeadView.onFinish(animEndListener)
- 新增支持Header(可以为任意类型)

##### fixed bugs
- 修复刷新或加载更多时，列表item没有铺满列表控件，滑动无效的问题
- 添加主动刷新/加载更多的方法：startRefresh(),startLoadMore()
- 修复顶部和底部越界高度不一致的问题
- 修复WebView在底部fling时不能越界的问题
- 动画执行时间与高度相关，动效更加柔和

**Comment by anmingyu11** [comment]
现在正在完善功能，等我彻底解决之后来提交request

**Comment by lcodecorex** [comment]
应该在这周末。改动有多大，难以想象😆

**Comment by lcodecorex** [comment]
你把你联系方式发我，我加你。邮箱lcodecore@163.com

**Comment by lcodecorex** [comment]
v1.04版发布，已修复问题！有彩蛋！！！
