### ISSUE TITLE
刷新或加载更多时，触摸事件就被禁掉了，想网络取消怎么办（使用者很有可能不想等待加载完成）？

### ISSUE THREAD

**Issue by xueyaolive** [lcodecorex/TwinklingRefreshLayout#24]

**Comment by lcodecorex** [comment]
@xueyaolive 目前这一版的逻辑是内容没能占满全屏时在刷新状态中时触摸事件无效。下一版可以多回调两个状态，onRefreshPause,onLoadmorePause供取消网络加载。非常感谢你的反馈！

**Comment by lcodecorex** [comment]
@xueyaolive v1.05给RefreshListenerAdapter添加了onRefreshCanceled()和onLoadmoreCanceled()接口
