### ISSUE TITLE
FixedHeader会挡住部分内容

### ISSUE THREAD

**Issue by yangheng09103** [lcodecorex/TwinklingRefreshLayout#27]
MusicActivity里的第一项就被完全遮住了

**Comment by lcodecorex** [comment]
@yangheng09103 Sorry。小问题，疏忽了，忘了requestLayout，稍后修复。下一版或许会采用CoordinateLayout的方式来实现。非常非常感谢你的反馈！

**Comment by lcodecorex** [comment]
@yangheng09103 已解决
