### ISSUE TITLE
内部有 ScrollView 时，内部无法获取到触摸事件。

### ISSUE THREAD

**Issue by Airsaid** [lcodecorex/TwinklingRefreshLayout#28]
不知道能不能进行优化呢？

**Comment by lcodecorex** [comment]
@Airsaid 是指内部的ScrollView的scrollListener无效吗？还是什么？

**Comment by Airsaid** [comment]
奇怪，回复的记录怎么没有了。。。 就是当 TwinklingRefreshLayout 内部有 ScrollView 嵌套时，滑动屏幕，只能响应到 TwinklingRefreshLayout 的事件。而  ScrollView 中的像 RecyclerView、ListView 都无法滑动。

**Comment by lcodecorex** [comment]
这个需要先解决ScrollView 和 RecyclerView、ListView嵌套使用的问题吧。本来它们嵌套滑动就是有冲突的，事件从上往下传递，只有在特定的场景RefreshLayout才会拦截事件，其它场景都传给ScrollView，所以冲突时ScrollView和它的子View之间的冲突。

**Comment by jiancao** [comment]
ListView的scrollListener监听不到怎么解决？
