### ISSUE TITLE
layout_behavior 支持

### ISSUE THREAD

**Issue by zhangle1** [lcodecorex/TwinklingRefreshLayout#29]
android.support.design.widget.CoordinatorLayout  使用这个包裹recyClerView
会和 AppBarLayout 有冲突，  头部异常。

**Comment by lcodecorex** [comment]
@zhangle1 好的，收到。下一版的主要方向就是兼容NestedScroll、CoordinatorLayout，我会尽快优化支持！

**Comment by timshinlee** [comment]
@lcodecorex 作者大大，最近项目有个比较特殊的需求，我通过以下两种方式实现，但是效果都不太好。
RefreshLayout[CoordinatorLayout(RecyclerView)]的组合中RecyclerView无法完全显示。
CoordinatorLayout[RefreshLayout(RecyclerView)]的组合中RecyclerView条数较少时滑动RecyclerView会触发上拉加载更多，无法带动AppBarLayout一起滑动，只能通过滑动AppBarLayout才能上拉完全显示RecyclerView，体验较差。不知能不能优先兼容一下CoordinatorLayout？感谢！

**Comment by lcodecorex** [comment]
@timshinlee 好的好的。看到你关注这个项目挺久了，哈哈，感谢！

**Comment by timshinlee** [comment]
@lcodecorex 是啊，因为项目做了好几个月，下拉刷新动画都靠您这个库，用起来比较方便。因为大部分情况很好用，但是有一些需求比较特殊不好解决，所以感觉像追小说一样，时不时上github看看有没有更新还是issue之类的 ;-) 衷心感谢！

**Comment by lcodecorex** [comment]
@timshinlee 目前已经兼容nestedscroll，在新版中内测，可以帮忙内测一下吗？qq群202640706

**Comment by lcodecorex** [comment]
v1.07版已修复！
