### ISSUE TITLE
关于加载更多时的回弹效果

### ISSUE THREAD

**Issue by luvictor** [lcodecorex/TwinklingRefreshLayout#30]
当需要加载更多时，应该关闭这个底部的回弹效果的。不然的话，向上滑动第一次是回弹， 第二次才是加载更多。 而且加载更多的时候，新的数据呈现在底部的那个动画可以省去。 类似于网易新闻，拖到底部就立即加载更多，并且不需要再次上拉才能看到新加载出来的内容

**Comment by lcodecorex** [comment]
@luvictor 我已经提供了相应的api来设置滑到底部时是要回弹还是加载更多。refreshLayout.setAutoLoadmore(true)即可。感谢反馈！
