### ISSUE TITLE
低版本不支持

### ISSUE THREAD

**Issue by xiangyunwan** [lcodecorex/TwinklingRefreshLayout#31]
发现有些低版本手机不支持，还有些酷派手机高版本也不支持。比如5.0系统。能把这些也兼容了就能用了，不然企业级，大版本，要求兼容性比较全的app，不能实现效果。希望借鉴。

**Comment by lcodecorex** [comment]
@xiangyunwan 理论上4.0以上版本都支持的，能不能把报错的日志发给我一下，lcodecore@163.com  感谢反馈！

**Comment by lcodecorex** [comment]
@xiangyunwan 能发一下报错的日志吗？

**Comment by xiangyunwan** [comment]
酷派手机我手上的测试机，系统5.0，不报错，但是没有效果。你找一个酷派手机试试吧
