### ISSUE TITLE
能否优化自动刷新的动画？还有

### ISSUE THREAD

**Issue by timshinlee** [lcodecorex/TwinklingRefreshLayout#33]
感谢作者写了一个这么简明易用的刷新库，不过我碰到两个小问题。
一个是调用startRefresh时自动刷新会直接跳到刷新动画，没有下拉的过程感觉比较突兀，不知道是我哪里写错或者这是可以优化的地方？
另外一个是refreshLayout和内部控件只能支持match_parent，如果都设成wrap_content，刷新动画会跑到屏幕中央，就是说refreshLayout没办法适配在非match_parent的情况下？不知道这个能不能添加支持一下？
作者大大辛苦了，十分感谢！

**Comment by lcodecorex** [comment]
@timshinlee 好的。正在修复几个小问题，发布之前会优化下这些问题。感谢反馈！

**Comment by timshinlee** [comment]
好的，十分感谢哈！

**Comment by lcodecorex** [comment]
@timshinlee 你是指Header只能支持macth_parent还是指的layout？能否代码贴出来参考下？邮箱 lcodecore@163.com

**Comment by lcodecorex** [comment]
@timshinlee  v1.06已做了优化，感谢反馈！
