### ISSUE TITLE
在Music视图中，刚好满一屏时没有回弹效果

### ISSUE THREAD

**Issue by tczyb** [lcodecorex/TwinklingRefreshLayout#35]
在Music视图中，刚好满一屏时（最后一个item只显示一半）没有回弹效果，item较多时不会。
当上述情况时，开启setAutoLoadMore(true)，不会加载，得上拉才能加载。

**Comment by lcodecorex** [comment]
@tczyb 这确实是个遗留的问题，fixedHeader的方案存在一点缺陷，下一版会借助CoordnatorLayout采用不一样的方案

**Comment by tczyb** [comment]
@lcodecorex 我已经把addFixedExHeader去掉了，还是一样

**Comment by lcodecorex** [comment]
@tczyb 能截图，代码，并说明详细情况吗？我的邮箱lodecore@163.com

**Comment by tczyb** [comment]
@lcodecorex 你邮箱写错了^_^

**Comment by lcodecorex** [comment]
v1.06已修复，感谢反馈！
