### ISSUE TITLE
加载更多完成时 会抖动  我该怎么修改

### ISSUE THREAD

**Issue by lizhifeng-sky** [lcodecorex/TwinklingRefreshLayout#37]

**Comment by lcodecorex** [comment]
@lizhifeng-sky 下一版来解决这个问题，开源库在不断完善。多谢反馈！

**Comment by lizhifeng-sky** [comment]
不好改吧 加载结束时listview滑动到加载动画的位置 ，加载动画会消失 这种原因产生的抖动不好改 不知所措。。。
TwinklingRefreshLayout  line671
ScrollingUtil.scrollAViewBy(mChildView, (int) mBottomHeight);
                 setLoadingMore(false);
                 animProcessor.animBottomBack();
你们的是想怎么改呢？

**Comment by lcodecorex** [comment]
v1.06已做了优化，感谢反馈！
