### ISSUE TITLE
fixedHeader中包含RecyclerView时，fixedHeader的RecyclerView无法滑动

### ISSUE THREAD

**Issue by timshinlee** [lcodecorex/TwinklingRefreshLayout#43]
业务需求要在fixedHeader中包含一个RecyclerView，但是滑动事件好像直接被refreshLayout拦截掉了，导致fixedHeader中的RecyclerView接收不到滑动事件？这个bug有办法解决吗？感谢！

**Comment by lcodecorex** [comment]
fixedHeader主要是提供来做广告位或者是轮播条的，加RecyclerView逻辑比较复杂，当时没有考虑到。暂时不好解决

**Comment by timshinlee** [comment]
好的，感谢！
