### ISSUE TITLE
关于滑动的目标View兼容问题。

### ISSUE THREAD

**Issue by ravenwang2012** [lcodecorex/TwinklingRefreshLayout#45]
经过查看源代码，目前获取子控件的方式为getChildAt(0)，但是在项目中经常会用到为一个嵌套布局进行刷新的情况，例如一个RelativeLayout嵌套了一个RecyclerView和一个TextView，这时用该框架就会出现问题。我之前修改过PtrFrameLayout，使用findViewWithTag的方式获取目标布局后无问题，但是修改完贵框架后屏幕出现白屏

**Comment by timshinlee** [comment]
考虑使用addFixedHeader?

**Comment by lcodecorex** [comment]
@ravenwang2012 问下你是需要怎么嵌套，我可以考虑添加一个需求，增加这个功能

**Comment by lcodecorex** [comment]
你好！我正在处理嵌套问题，请加qq群202640706我们一起分析一下问题！

**Comment by lcodecorex** [comment]
@timshinlee 请加QQ群202640706我们一起分析下兼容NestedScroll的需求

**Comment by lcodecorex** [comment]
v1.07版已修复！
