### ISSUE TITLE
compile 'com.wang.avi:library:1.0.1'依赖太旧

### ISSUE THREAD

**Issue by supersugar** [lcodecorex/TwinklingRefreshLayout#46]
正好本人项目中用到compile 'com.wang.avi:library:2.1.3'
而TwinklingRefreshLayout中是1.0.1版本
这样运行就会报错了,请问可以升级一下该依赖吗?

**Comment by kstg3646426** [comment]
同遇到该问题。。。

**Comment by chimis** [comment]
同上

**Comment by lcodecorex** [comment]
@supersugar @kstg3646426 @chimis v1.06已经去除了依赖，感谢反馈！
