### ISSUE TITLE
为什么不能下拉刷新

### ISSUE THREAD

**Issue by kstg3646426** [lcodecorex/TwinklingRefreshLayout#47]
为什么滑动不能下拉刷新，但是调用startRefresh能出来，滑动就出不来，难道是我打开方式不正确？

**Comment by timshinlee** [comment]
可能控件没有获取到焦点？我有碰到过代码中设置控件获取焦点后才能正常下拉的情况

**Comment by lcodecorex** [comment]
@kstg3646426 能描述的更详细一点吗？我好确认并定位问题

**Comment by lcodecorex** [comment]
v1.06已修复，感谢反馈！
