### ISSUE TITLE
三星手机会出现兼容问题

### ISSUE THREAD

**Issue by YangMian** [lcodecorex/TwinklingRefreshLayout#49]
使用TwinklingRefreshLayout时， 在三星手机出现点击listview的item 无响应， 多点几下这个item 才能获取到点击事件， 这个体验非常糟糕。 小米和华为手机上测试不会出现类似情况。 作者是否可以更新一下，感谢作者的开源

**Comment by lcodecorex** [comment]
你好！感谢你的反馈，我会尽快修复更新
