### ISSUE TITLE
上拉加载更多拉出全部View后没法继续拉动

### ISSUE THREAD

**Issue by WenHuayu** [lcodecorex/TwinklingRefreshLayout#51]
setWaveHeight只能设置下拉刷新的

**Comment by lcodecorex** [comment]
@WenHuayu 感谢反馈！问题可以描述的具体一点吗？

**Comment by WenHuayu** [comment]
我写的测试中，设置了setWaveHeight后，下拉刷新可以拉动到更下方的位置，松手后回到刷新位置开始刷新动画。但是上拉刷新拉动到一定位置后，界面就被固定了，没法继续上拉。查看源码后发现RefreshProcessor#consumeTouchEvent方法中，下拉刷新取dy用的dy = Math.min(cp.getMaxHeadHeight() * 2, dy);上拉加载取dy用的dy = Math.min(cp.getBottomHeight() * 2, Math.abs(dy));
