### ISSUE TITLE
1.0.6更新后fixheadView有个大问题

### ISSUE THREAD

**Issue by helixs** [lcodecorex/TwinklingRefreshLayout#55]
![f8385f2f-c56c-4bae-987d-00cd2667a067](https://cloud.githubusercontent.com/assets/20335861/23790119/b59a857e-05b8-11e7-9507-b4b9d153cb6a.png)
fixheadView会盖住head

**Comment by helixs** [comment]
所以导致了 设置setFloatRefresh(true) 会看不到下拉刷新

**Comment by lcodecorex** [comment]
收到。好的，尽快修复！
