### ISSUE TITLE
我日啊，包裹FrameLayout有问题啊

### ISSUE THREAD

**Issue by txxxtxx** [lcodecorex/TwinklingRefreshLayout#58]
我日啊，包裹FrameLayout有问题啊，我的FrameLayout里面放的RecyclerView，上拉之后，RecyclerView跑到上面去了，我日，既然都写成这样了，干脆把loading，empty，error的界面也弄进去啊，我之所以放framelayout就是因为我写的loadinglayout是继承framelayout的，红色是match_parent的framelayout，RecyclerView也是match_parent的。
![wechatimg1](https://cloud.githubusercontent.com/assets/10277897/23849017/a6afc3ea-0814-11e7-8021-e417292ec639.jpeg)

**Comment by lcodecorex** [comment]
你说的是RecyclerView固定在上面了，还是没有弹回去？

**Comment by txxxtxx** [comment]
固定在上面了，没有弹回去

**Comment by lcodecorex** [comment]
能分享你的布局和相关逻辑我好调试一下吗？ lcodecore@163.com

**Comment by txxxtxx** [comment]
我试了一下Relativelayout里面包recyclerview也是一样的，不过我调整了一下，用loadinglayout包TwinklingRefreshLayout了，这样就可以避免我刚刚说的问题了。

**Comment by lcodecorex** [comment]
LoadingLayout是什么？

**Comment by txxxtxx** [comment]
我自己写的一个布局根据情况显示loading，empty，error界面的

**Comment by lcodecorex** [comment]
不太能看懂你前面说的布局的嵌套是什么样的

**Comment by txxxtxx** [comment]
TwinklingRefreshLayout->FramLayout-> recyclerview 这样有问题，上拉之后recyclerview会跑到上面去回不来

**Comment by lcodecorex** [comment]
有调用setTargetView方法吗？

**Comment by txxxtxx** [comment]
并没有 布局里面引用的TwinklingRefreshLayout

**Comment by lcodecorex** [comment]
你需要在代码里面setTargetView设置滚动的目标。因为你这个嵌套了，而控件默认的滚动view是控件的直接子类

**Comment by lcodecorex** [comment]
直接子View

**Comment by txxxtxx** [comment]
还有个问题，如果我的数据加载完成了，上拉的时候想显示没有更多数据了，这时候应该怎么弄？

**Comment by ailuoyi** [comment]
看来开源也是需要有强大心理素质的

**Comment by lcodecorex** [comment]
你好！我正在处理嵌套问题，请加qq群202640706我们一起分析一下问题！

**Comment by rainbowBin** [comment]
如果我的数据加载完成了，上拉的时候想显示没有更多数据了，这时候应该怎么弄？
