### ISSUE TITLE
当item不满一屏时，也可执行loadmore

### ISSUE THREAD

**Issue by tczyb** [lcodecorex/TwinklingRefreshLayout#59]
当item不满一屏时，也可执行loadmore，能否改成满屏时才可执行？

**Comment by lcodecorex** [comment]
这个你在代码里控制就好。你提的这个需求不能满足所有人。比如你想要加载15条数据，结果只得到了5条，说明数据加载完了，这个时候你就可以设置禁用加载很多

**Comment by lcodecorex** [comment]
v1.07版已修复！
