### ISSUE TITLE
底部上拉问题

### ISSUE THREAD

**Issue by zbldgit** [lcodecorex/TwinklingRefreshLayout#60]
这个框架只能先上拉到最低端， 然后停住。在最底端时继续上拉才执行loadmore吗，不能直接拖出footview吗

**Comment by Gitupstar** [comment]
问题同上

**Comment by 79660095** [comment]
大兄弟 文档里面有的setAutoLoadMore 滑动到底部自动加载

**Comment by lcodecorex** [comment]
@zbldgit @Gitupstar 设置下setAutoLoadMor(true)方法就好了
