### ISSUE TITLE
有内存泄漏问题

### ISSUE THREAD

**Issue by xiang473535976** [lcodecorex/TwinklingRefreshLayout#61]
用的是BezierLayout  安卓版本4.4  leakcanary 检测到的   请看看哈

**Comment by lcodecorex** [comment]
请截一下图哦

**Comment by xiang473535976** [comment]
![screenshot_2017-03-15-15-21-04_com cddgg oasys](https://cloud.githubusercontent.com/assets/18111614/23937597/4fde894a-0993-11e7-85c3-d6f6bfb5805d.png)
用的是BezierLayout这个头部   谢谢  请帮忙处理哈  现在项目中 在用

**Comment by lcodecorex** [comment]
看好了哦，不是BeizierLayout泄漏了，是你的AudioManager泄漏了

**Comment by xiang473535976** [comment]
好的  我明天再看看哈 谢了
