### ISSUE TITLE
1.0.6滑动事件冲突

### ISSUE THREAD

**Issue by MartinDong** [lcodecorex/TwinklingRefreshLayout#63]
讲真，升级1.0.6后明显感觉嵌套RecycleView的那个时间冲突很严重，以及刷新的效果头部动画。都不及以前的好用了，是不是作者的代码没有提交全呀

**Comment by lcodecorex** [comment]
代码上是去除了一些滚动监听器之类的，动画方面做的改动就是消除了animator的内存泄漏。能具体描述一下使用场景吗？我继续优化下

**Comment by Einsteinford** [comment]
其实我用1.05版本添加RecycleView也出现了问题，API19的机子流程，但API21的机子，大约手指从底部滑到半个屏幕，不会有惯性移动效果，滑动很慢

**Comment by lcodecorex** [comment]
@Einsteinford 这个问题必现吗？

**Comment by Einsteinford** [comment]
我再测试下，毕竟多重嵌套，手边的测试机都试完后再看看是什么问题

**Comment by lcodecorex** [comment]
多重嵌套啊，其实设计的时候考虑的是直接嵌套的，如果是多级嵌套（recyclerView不是RefreshLayout的直接子View的情况），要调用下refreshLayout.setTargetView(recyclerView)方法。

**Comment by lcodecorex** [comment]
你好！我正在处理嵌套问题，请加qq群202640706我们一起分析一下问题！

**Comment by lcodecorex** [comment]
@MartinDong @Einsteinford 新版已经修复上述问题，欢迎来qq群内测，202640706

**Comment by lcodecorex** [comment]
v1.07版已修复！
