### ISSUE TITLE
上拉加载更多的问题

### ISSUE THREAD

**Issue by yswheye** [lcodecorex/TwinklingRefreshLayout#7]
上拉加载更多的问题，每次到底部之后还要再向上拉一下才加载。这样体验很不好，应该是到底部之后就显示底部loading开始加载。

**Comment by guoyoujin** [comment]
我也发现这个问题。正在看代码的走向，找到关键代码告诉你

**Comment by lcodecorex** [comment]
收到。之后我会添加一个auto load的逻辑

**Comment by lcodecorex** [comment]
@yswheye @guoyoujin v1.04版发布，已优化问题！有彩蛋！！！
