### ISSUE TITLE
设置了头部的样式  但还是不会变  换了个手机就是设置后的样式

### ISSUE THREAD

**Issue by zhangli915952504** [lcodecorex/TwinklingRefreshLayout#70]
![img_20170323_100836](https://cloud.githubusercontent.com/assets/15918114/24228829/87c2e6c0-0fb1-11e7-97cb-8871ff6e40ad.jpg)

在7.0的手机上 就可以  中间包的是一个scrollview  很奇怪

**Comment by lcodecorex** [comment]
@zhangli915952504 问题解决了吗？我感觉可能会是instant run的问题。可以加qq群202640706我们分析一下问题

**Comment by lcodecorex** [comment]
v1.07版已修复！
