### ISSUE TITLE
怎么下载不下来 报 502

### ISSUE THREAD

**Issue by DominateFutureOK** [lcodecorex/TwinklingRefreshLayout#71]

**Comment by lcodecorex** [comment]
你是说jcenter仓库还是github项目？

**Comment by DominateFutureOK** [comment]
github项目 


------------------ 原始邮件 ------------------
发件人: "lcodecorex";<notifications@github.com>;
发送时间: 2017年3月24日(星期五) 下午2:04
收件人: "lcodecorex/TwinklingRefreshLayout"<TwinklingRefreshLayout@noreply.github.com>; 
抄送: "☆∮胜胜∫★"<290101428@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lcodecorex/TwinklingRefreshLayout] 怎么下载不下来 报 502 (#71)




你是说jcenter仓库还是github项目？

**Comment by DominateFutureOK** [comment]
点击下载 就这样了。
------------------ 原始邮件 ------------------
发件人: "lcodecorex";<notifications@github.com>;
发送时间: 2017年3月24日(星期五) 下午2:04
收件人: "lcodecorex/TwinklingRefreshLayout"<TwinklingRefreshLayout@noreply.github.com>; 
抄送: "☆∮胜胜∫★"<290101428@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lcodecorex/TwinklingRefreshLayout] 怎么下载不下来 报 502 (#71)




你是说jcenter仓库还是github项目？

**Comment by lcodecorex** [comment]
里面视频，demo太大的原因

**Comment by DominateFutureOK** [comment]
昨办？






------------------ 原始邮件 ------------------
发件人: "lcodecorex";<notifications@github.com>;
发送时间: 2017年3月24日(星期五) 下午2:10
收件人: "lcodecorex/TwinklingRefreshLayout"<TwinklingRefreshLayout@noreply.github.com>; 
抄送: "☆∮胜胜∫★"<290101428@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lcodecorex/TwinklingRefreshLayout] 怎么下载不下来 报 502 (#71)




里面视频，demo太大的原因

**Comment by lcodecorex** [comment]
https://codeload.github.com/lcodecorex/TwinklingRefreshLayout/zip/master  用迅雷下这个链接吧。 下好改成zip解压

**Comment by DominateFutureOK** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "lcodecorex";<notifications@github.com>;
发送时间: 2017年3月24日(星期五) 下午2:18
收件人: "lcodecorex/TwinklingRefreshLayout"<TwinklingRefreshLayout@noreply.github.com>; 
抄送: "☆∮胜胜∫★"<290101428@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lcodecorex/TwinklingRefreshLayout] 怎么下载不下来 报 502 (#71)




https://codeload.github.com/lcodecorex/TwinklingRefreshLayout/zip/master  用迅雷下这个链接吧。 下好改成zip解压
