### ISSUE TITLE
在 xml中配置tr_enable_loadmore不起作用, 必须在代码中调用setEnableLoadmore才其作用

### ISSUE THREAD

**Issue by zzh1026** [lcodecorex/TwinklingRefreshLayout#74]
在 xml中配置swip:tr_enable_loadmore="false"不起作用, 必须在代码中调用refreshLayout.setEnableLoadmore(false)才起作用 , 这是怎么回事呢?是不是xml中的一些配置不起作用啊

**Comment by lcodecorex** [comment]
好的。感谢反馈！我测试一下

**Comment by zzh1026** [comment]
你好, 在设置是否可以加载更多的时候
public void setEnableLoadmore(boolean enableLoadmore1) {
        enableLoadmore = enableLoadmore1;
        if (mBottomView != null) {
            if (enableLoadmore) mBottomView.getView().setVisibility(VISIBLE);
            else mBottomView.getView().setVisibility(GONE);
        }
    }
但是在设置是否可以下拉加载更多的时候
public void setEnableRefresh(boolean enableRefresh1) {
        this.enableRefresh = enableRefresh1;
    }
这块没有更新,所以没有起作用吧, 应该这里也得隐藏控件布局的.
然后在初始话的时候 addHeader,和addFooter 的时候没有根据是否隐藏头尾布局来进行控件隐藏

**Comment by lcodecorex** [comment]
v1.07版已修复！
