### ISSUE TITLE
demo在Samsung SM-N7508V android 4.3 有问题

### ISSUE THREAD

**Issue by lhx546920268** [lcodecorex/TwinklingRefreshLayout#75]
向上滑动时，如果没有停止滑动，是不会触发上拉加载的，必须把手指移开再继续上拉才触发，而且只有滑到最底部时上拉才会触发，同理，下拉刷新也一样

**Comment by lcodecorex** [comment]
这个涉及到了nestedscroll，稍后会修复

**Comment by lcodecorex** [comment]
@lhx546920268 感谢反馈！新版已支持这个功能，正在内测，可以来帮忙内测一下吗？qq群202640706
