### ISSUE TITLE
关于禁止加载更多后的一个小问题

### ISSUE THREAD

**Issue by ailuoyi** [lcodecorex/TwinklingRefreshLayout#76]
感谢lcodecorex大神的无私开源。打扰一下。在使用的时候遇到一个问题，烦请lcodecorex过目一下：
一般流程是这样：当上拉加载更多没有数据后会调用twinklingRefreshLayout.setEnableLoadmore(false);这样再次上拉就不会再去请求数据，TwinklingRefreshLayout的onPullingDown也做了对enableLoadmore的判断。但此种情况下，当RecyclerView处于SCROLL_STATE_IDLE状态时仍然会回调出来。能否在twinklingRefreshLayout#onLoadMore()方法中也增加对enableLoadmore的判断或对外暴露enableLoadmore。

**Comment by lcodecorex** [comment]
@ailuoyi 加qq群详细讨论一下，202640706
