### ISSUE TITLE
demo体验时发现的问题

### ISSUE THREAD

**Issue by yutf** [lcodecorex/TwinklingRefreshLayout#8]
demo里gridview下拉时，在“下拉刷新”状态即将切换到“释放”状态时，此时抬起手指，刷新控件并没有收起，这个是demo层的问题还是TwinklingRefreshLayout的问题？

**Comment by lcodecorex** [comment]
那个是旧版的demo，是demo的问题，收起手动调用finishRefresh()即可

**Comment by lcodecorex** [comment]
@yutf 那个是旧版的demo，是demo的问题，收起手动调用finishRefresh()即可
