### ISSUE TITLE
第二次下拉刷新的下拉两次才有效果

### ISSUE THREAD

**Issue by tczyb** [lcodecorex/TwinklingRefreshLayout#80]
第二次下拉刷新要下拉两次才有效果

**Comment by lcodecorex** [comment]
你好！非常感谢你及时的反馈了问题。该问题已经修复。请删除Android studio中缓存的相应的jar包并重新sync！（jar包位置可以在AS中找到）

**Comment by yuxinLi** [comment]
哪个版本修复的， 我手机有这个问题

**Comment by yuxinLi** [comment]
我是最新的
