### ISSUE TITLE
如何自动（主动）刷新？

### ISSUE THREAD

**Issue by icodero** [lcodecorex/TwinklingRefreshLayout#9]
我想在Activity/Fragemnt中手动调用refresh方法，并呈现刷新动画，不是通过事件回调的方式。
如：mSwipeRefreshLayout.setRefreshing(true);
请问如何实现或调用？

**Comment by lcodecorex** [comment]
主动刷新的逻辑现在还没有加，稍后版本会加上，尽量完善

**Comment by BarryLiu1995** [comment]
我也想问同样的问题来着，希望赶快加入这一功能，或者单独把动画实现的逻辑写上去

**Comment by lcodecorex** [comment]
这一版发布就会实现

**Comment by lcodecorex** [comment]
@icodero @BarryLiu1995  v1.04版发布，已修复问题！有彩蛋！！！
