### ISSUE TITLE
没有拉到顶，或者到底就会触发加载，怎么办

### ISSUE THREAD

**Issue by liunewshine** [lcodecorex/TwinklingRefreshLayout#93]
![image](https://cloud.githubusercontent.com/assets/7698511/25572685/2e992b94-2e70-11e7-9882-cab21a385aef.png)

**Comment by liunewshine** [comment]
refreshLayout放在viewpager外层的

**Comment by timshinlee** [comment]
好像refreshlayout要放在viewpager里面才行
